Added missing curly brace for #ifdef __cplusplus
nrfconnect/sdk-mcu-drivers pull request #3
Opened 2023-11-07 13:55 UTC by moritzstoetter

2023-11-20 08:26 UTC, moritzstoetter commented
Hey contributors @koffes @alexsven any chance of getting this merged? Or maybe it's time for updating the fork? This bug is not present in the upstream.

2023-11-27 06:51 UTC, alexsven approved these changes

2023-11-27 07:52 UTC, koffes approved these changes

2023-11-27 07:56 UTC, koffes commented
@moritzstoetter Thanks for the PR. Please squash the two commits.

2023-11-27 07:57 UTC, koffes requested changes
Thanks for the PR. Please squash the two commits.

2023-11-27 08:53 UTC, moritzstoetter commented
Done 👍

2023-11-29 14:21 UTC, koffes approved these changes

2023-11-29 14:24 UTC, merged

2023-11-29 14:34 UTC, koffes commented
Manifest update here: https://github.com/nrfconnect/sdk-nrf/pull/13283